### PR TITLE
Add Laravel 9 support

### PR DESCRIPTION
**Pull request by francoism90**

### CODE REVIEW

**Comment by RickvdStaaij** [comment]
@sharifzadesina @korridor @onlime could you verify and tag a new version please? :) Would love to keep using this library with Laravel 9

**Comment by korridor** [comment]
@RickvdStaaij Unfortunately I'm not a maintainer and so I can't tag a new version. But I would be happy about Laravel 9 support as well.

**Comment by onlime** [comment]
@RickvdStaaij Same here. I'm not a maintainer but would also very much appreciate Laravel 9 support.

**Comment by sharifzadesina** [comment]
Thanks, merged.

**Comment by RickvdStaaij** [comment]
Thank you! And sorry for the wrong pings :wink: :ok_hand:

**Comment by francoism90** [comment]
Thanks for the merge! :)

**Pull request merged**
